{{- if .Values.site24x7ClusterAgent.create }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "site24x7-agent.fullname" . }}-cluster-agent
  labels:
    {{- include "site24x7ClusterAgent.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.site24x7ClusterAgent.replicas | default 1 }}
  selector:
    matchLabels:
      {{- include "site24x7-agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "site24x7ClusterAgent.labels" . | nindent 8 }}
        app: {{ include "site24x7-agent.fullname" . }}-cluster-agent
      name: {{ include "site24x7-agent.fullname" . }}-cluster-agent
    spec:
      serviceAccountName: site24x7
      containers:
      - image: site24x7/docker-agent:cluster_agent_nonroot
        imagePullPolicy: Always
        name: site24x7-cluster-agent
        env:
          - name: NODE_IP
            valueFrom:
              fieldRef:
                  fieldPath: status.hostIP
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: CLUSTER_AGENT
            value: "true"
        ports:
          - containerPort: 5000
            name: http-metrics
            protocol: TCP
        securityContext:
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1001010001
        volumeMounts:
          - name: site24x7-cluster-agent
            mountPath: /home/site24x7/monagent
        resources:
          requests:
            memory: "50Mi"
            cpu: "50m"
          limits:
            memory: "450Mi"
            cpu: "400m"
        livenessProbe:
          httpGet:
            path: /ca/health_check
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 20
          failureThreshold: 5
          timeoutSeconds: 15
        readinessProbe:
          httpGet:
            path: /ca/health_check
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 15
          failureThreshold: 5
          timeoutSeconds: 10
      volumes:
      - emptyDir: {}
        name: site24x7-cluster-agent
{{ end }}