apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "site24x7-agent.fullname" . }}-agent
  labels:
    - app.kubernetes.io/name: {{ include "site24x7-agent.name" . }}
    {{- include "site24x7-agent.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "site24x7-agent.selectorLabels" . | nindent 4 }}
  updateStrategy:
    {{- if not (empty .Values.site24x7Agent.updateStrategy) }}
    {{- toYaml .Values.site24x7Agent.updateStrategy | nindent 4 }}
    {{- else }}
    type: RollingUpdate
    {{- end }}
  template:
    metadata:
      labels:      
        {{- include "site24x7-agent.labels" . | nindent 8 }}
      name: {{ include "site24x7-agent.fullname" . }}-agent
    spec:
      serviceAccountName: {{ include "site24x7-agent.fullname" . }}          
      nodeSelector:
        {{- include "site24x7-agent.nodeSelector" . | nindent 8 }}
      tolerations:
        {{- toYaml .Values.site24x7Agent.tolerations | nindent 8 }}
      containers:
        {{- include "site24x7-agent.container" . | nindent 8 }}
      volumes:
        {{- include "site24x7-agent.volumes" . | nindent 8 }}