{{- if .Values.site24x7KubeStateMetrics.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "site24x7-agent.labels" . | nindent 4 }}
  name: {{ include "site24x7-agent.fullname" . }}-kube-state-metrics
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "site24x7-agent.fullname" . }}-kube-state-metrics
  template:
    metadata:
      labels:
        {{- include "site24x7-agent.labels" . | nindent 8 }}
        app.kubernetes.io/version: 2.9.2
        app: site24x7-kube-state-metrics
    spec:
      tolerations:
        {{- toYaml .Values.site24x7KubeStateMetrics.tolerations | nindent 8 }}
      automountServiceAccountToken: true
      containers:
        {{- include "site24x7.kube-state-metrics" . | nindent 8 }}
      nodeSelector:
        {{- if not (empty .Values.site24x7Agent.nodeSelector) -}}
        {{- .Values.site24x7Agent.nodeSelector }}
        {{- else -}}
        kubernetes.io/os: linux
        {{- end }}
      serviceAccountName: {{ include "site24x7-agent.fullname" . }}-kube-state-metrics
{{- end }}